[options]
  # spacevim update policy
  automatic_update = false

  # set spacevim theme.
  colorscheme = "gruvbox"
  colorscheme_bg = "dark"

  # 24bit ture colors
  enable_guicolors = true

  # statusline
  enable_statusline_mode = false
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  enable_tabline_filetype_icon = false
  buffer_index_type = 4

  # disabled some unused plugins
  disabled_plugins = ["heavenshell/vim-jsdoc", "Galooshi/vim-import-js", "maksimr/vim-jsbeaufify"]

[[layers]]
name = "autocomplete"
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = "shell"
default_position = "top"
default_height = 30

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#typescript"
